### PR TITLE
Fix #181: default the metadata version from the IBP version in the same manner as StorageTool to enable SCRAM support.

### LINKED ISSUE #181: Storage format selected does not support SASL SCRAM
For my use-case, I want to configure the Cluster to use SCRAM-SHA username and password.  This works with Zookeeper based clusters (SCRAM user db is held in Zookeeper), but fails on KRaft (SCRAM user db is held in broker storage) .  This reason is the storage format hardcoded by kafka-native is too old.

```
java.util.concurrent.CompletionException: org.apache.kafka.common.errors.UnsupportedVersionException: The current metadata version does not support SCRAM

	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at io.kroxylicious.testing.kafka.common.Utils.createUsersOnClusterIfNecessary(Utils.java:183)
	at io.kroxylicious.testing.kafka.testcontainers.TestcontainersKafkaCluster.start(TestcontainersKafkaCluster.java:344)
	at io.kroxylicious.testing.kafka.KafkaClusterTest.kafkaClusterWithUsernamePasswordBasedSaslAuth(KafkaClusterTest.java:360)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: The current metadata version does not support SCRAM
```

### PR DESCRIPTION
**Pull request by k-wall**
When `StorageTool` formats the storage it defaults the metadata format from the IBP version (`inter.broker.protocol.version`).  If the `inter.broker.protocol.version` property is not present, it defaults to `MetadataVersion#LATEST_PRODUCTION`.  This change has the `EmbeddedBroker` adopt the same behaviour.

I'm thinking that adopting the behaviour of BrokerTool is least surprise.  This does however mean that there is a behavioural change: the kafka-native brokers will use the `LATEST_PRODUCTION` metadata version by default.  Users will be able to get back the old behaviour by specifying `inter.broker.protocol.version` in their configuration files.

It also adds any scram specified Scram using into the store (KRaft metadata or Zookeeper).

### CODE REVIEW

**Comment by k-wall** [comment]
I need to make further changes to this PR.

**Comment by ozangunalp** [comment]
@k-wall I've pushed a change to add scram credentials to the storage format.

**Comment by k-wall** [comment]
hey, you read my mind!  That's exactly what I intended to add!  Let me review the change.  Thank you.

**Comment by ozangunalp** [comment]
@k-wall Thanks for the test! 

There is still a catch for passing the scram_credentials config to the application. Because the config receives a list of credential strings separated by comma, you need to escape all other commas. 

I am thinking of using semicolon instead of comma to separate credential strings.

**Comment by k-wall** [comment]
Yes I noticed the comma issue. Semi colon works find.

I'm just working on a change to support the equivalent on the Zookeeper path.  I hope to push a change soon.

**Comment by k-wall** [comment]
@ozangunalp Your changes lgtm btw

**Comment by ozangunalp** [comment]
@k-wall Why don't we include the zk scram credentials provisioning _only_ in the `zookeeper-server` ?

It makes sense for the zookeeper-server to start with those credentials, but, for me running the kafka-server in zk-mode, I'd expect that the credentials would be provisioned during an infrastructure configuration action. 

wdyt ?

**Comment by ozangunalp** [comment]
btw I've the change to use semicolon for Scram Credentials list, I'll push once we agree on your change.

**Comment by k-wall** [comment]
> @k-wall Why don't we include the zk scram credentials provisioning only in the zookeeper-server ?

Zookeeper-native is completely generic. It knows nothing about how it will be used.    The scram users on the other hand are purely Kafka's concern and get represented in Zk in a Kafka specific way.
 
Once we reach Kafka 4.0, we'll be able to strip out the Zookeeper code and dependencies.  Hopefully that won't be too long.

 
The scram users belong to Kafka

**Comment by ozangunalp** [comment]
Fair enough. I agree. I'll push a change to fix the comma issue.

**Review by k-wall — COMMENTED** [review]
lgtm, thank you @ozangunalp

**Comment by k-wall** [comment]
@ozangunalp could you approve this?  I'd like to rerun the release for 3.7.0 so there is an image with this capability.

**Review by ozangunalp — APPROVED** [review]

**Pull request merged**
